### ISSUE TITLE
Gulp issue

### ISSUE THREAD

**Issue by mindfu** [planetoftheweb/angulardata_old#1]
Ray, getting these errors when trying to run Gulp for the first time after installation:

[18:49:47] Using gulpfile c:\xampp\htdocs\angulardata\gulpfile.js
[18:49:47] Starting 'watch'...
[18:49:47] Finished 'watch' after 18 ms
[18:49:47] Starting 'html'...
[18:49:47] Finished 'html' after 4.28 ms
[18:49:47] Starting 'js'...
[18:49:47] Finished 'js' after 2.95 ms
[18:49:47] Starting 'css'...
[18:49:47] Finished 'css' after 1.92 ms
[18:49:47] Starting 'webserver'...
[18:49:47] Webserver started at http://localhost:8000
[18:49:47] Finished 'webserver' after 8.07 ms
[18:49:47] Starting 'default'...
[18:49:47] Finished 'default' after 7.8 μs

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3

Any suggestions?

**Comment by planetoftheweb** [comment]
I'm not really sure. I sometimes get an EACCESS error when I try to run more than one copy of the gulp command. Make sure you close all terminals and try again. Also, make sure you aren't running a separate copy of something like LiveReload, Prepros or CodeKit.

**Comment by planetoftheweb** [comment]
I really don't. Node errors seem to be cryptic. I think this is a symptom of another problem. Make sure your reboot after installing things on a windows machines. I know that has caused problems in the past.

**Comment by mindfu** [comment]
I will try to work on this again or setup on another machine.  Just wanted to say I really enjoyed your angular course tremendously.  It might be the best online course I have ever taken because of its clarity, well constructed, and thorough.  Really really excellent.  Just wanted to tell you.  Hope to run through all the examples once I get setup.  Thanks Ray!

**Comment by planetoftheweb** [comment]
Thanks, I'm going to be updating this course in a few weeks because of some changes to the authentication and then I'll be doing a related course on Angular for Mobile using the Ionic framework, so stay tuned. My blog (which I'm doing with Jeklyll is raybo.org) or you can follow me on twitter @planetoftheweb for updates.

**Comment by shruts2907** [comment]
@mindfu did you solve the issue. I am getting the same after running gulp command?

**Comment by planetoftheweb** [comment]
EACCESS for me is always when there are multiple copies of livereload working, so I don't believe this is an error with the course. By the way, I updated this course to work with the new firebase authentication rules. It will be a while before the video is updated, but the project is here: https://github.com/planetoftheweb/angulardatau

**Comment by mindfu** [comment]
Did not solve.  Sorry @shruts2907

**Comment by shruts2907** [comment]
@planetoftheweb  my webserver started at port 8000 in Readme you said to open browser at 8080. Is this causing error? How should I solve it?

Shruts@SHRUTS-VAIO /c/xampp/htdocs/ng/angulardata (master)
$ gulp
[00:09:19] Using gulpfile c:\xampp\htdocs\ng\angulardata\gulpfile.js
[00:09:19] Starting 'watch'...
[00:09:19] Finished 'watch' after 29 ms
[00:09:19] Starting 'html'...
[00:09:19] Finished 'html' after 4.47 ms
[00:09:19] Starting 'js'...
[00:09:19] Finished 'js' after 990 µs
[00:09:20] Starting 'css'...
[00:09:20] Finished 'css' after 714 µs
[00:09:20] Starting 'webserver'...
[00:09:20] Webserver started at http://localhost:8000
[00:09:20] Finished 'webserver' after 7.63 ms
[00:09:20] Starting 'default'...
[00:09:20] Finished 'default' after 8.03 µs

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at dns.js:72:18
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by planetoftheweb** [comment]
Did yo try running it on port 8080? Maybe on PCs it opens another port.

-- 
Ray Villalobos

On February 17, 2015 at 3:24:02 AM, Shrutika (notifications@github.com) wrote:

@planetoftheweb my webserver started at port 8000 in Readme you said to open browser at 8080. Is this causing error? How should I solve it?

Shruts@SHRUTS-VAIO /c/xampp/htdocs/ng/angulardata (master)
$ gulp
[00:09:19] Using gulpfile c:\xampp\htdocs\ng\angulardata\gulpfile.js
[00:09:19] Starting 'watch'...
[00:09:19] Finished 'watch' after 29 ms
[00:09:19] Starting 'html'...
[00:09:19] Finished 'html' after 4.47 ms
[00:09:19] Starting 'js'...
[00:09:19] Finished 'js' after 990 µs
[00:09:20] Starting 'css'...
[00:09:20] Finished 'css' after 714 µs
[00:09:20] Starting 'webserver'...
[00:09:20] Webserver started at http://localhost:8000
[00:09:20] Finished 'webserver' after 7.63 ms
[00:09:20] Starting 'default'...
[00:09:20] Finished 'default' after 8.03 µs

events.js:72
throw er; // Unhandled 'error' event
^
Error: listen EACCES
at errnoException (net.js:905:11)
at Server._listen2 (net.js:1024:19)
at listen (net.js:1065:10)
at net.js:1147:9
at dns.js:72:18
at process._tickCallback (node.js:442:13)
at Function.Module.runMain (module.js:499:11)
at startup (node.js:119:16)
at node.js:929:3

**Comment by shruts2907** [comment]
Yes the project opens at 8080 but I still get the error on my git bash when I run gulp command. Should I ignore the error and move forward with the project?

**Comment by makinwa37** [comment]
Ps. Having the same issue when running the gulp command.
